[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd frontend && npm install", "cd backend && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build", "cd backend && npm run build"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
